Folder Restructure and Image Decompressing
Interbotix/act pull request #5
Opened 2024-07-10 16:30 UTC by shantanuparab-tr

1. **Folder Restructure** 
The act module is not detected when scripts are placed in the /scripts folder. Moved the script to /act folder and updated the import statements accordingly.
3. **Decompress Images** 
The images recorded in the .hdf5 episodes are in compressed format, this causes issue with tensor size mismatch in torch.einsum() method. 
Added a compressed flag which is extracted from the .hdf5 file to decompress the images when required.

2024-07-11 21:50 UTC, lukeschmitt-tr requested changes

2024-07-11 21:50 UTC, lukeschmitt-tr commented on act/scripts/imitate_episodes.py
Make sure to remove the old script file

2024-07-15 15:38 UTC, shantanuparab-tr commented
Removed the old scripts folder

2024-07-15 15:44 UTC, shantanuparab-tr commented on act/scripts/imitate_episodes.py
Removed the old scripts folder

2024-07-15 15:46 UTC, lukeschmitt-tr requested changes

2024-07-15 15:46 UTC, lukeschmitt-tr commented on .gitignore
> +
```suggestion
```

2024-07-15 15:46 UTC, lukeschmitt-tr commented on act/imitate_episodes.py
> +    # sys.exit()
```suggestion
```

2024-07-15 15:46 UTC, lukeschmitt-tr approved these changes

2024-07-15 15:57 UTC, merged